import React from 'react';
import { BookOpen, Info } from 'lucide-react';

export const LearnHub: React.FC = () => {
  const terms = [
    { term: 'Carbon Footprint', desc: 'The total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.' },
    { term: 'CO₂e', desc: 'Carbon Dioxide Equivalent. A standard unit for measuring carbon footprints. It expresses the impact of each different greenhouse gas in terms of the amount of CO2 that would create the same amount of warming.' },
    { term: 'kgCO₂e', desc: 'Kilograms of Carbon Dioxide Equivalent. Used for everyday items like food and daily transport.' },
    { term: 'tCO₂e', desc: 'Tonnes of Carbon Dioxide Equivalent (1,000 kg). Used for annual personal footprints or small businesses.' },
    { term: 'MtCO₂e', desc: 'Megatonnes of Carbon Dioxide Equivalent (1 Million tonnes). Used for national or sector-level emissions.' },
    { term: 'GtCO₂e', desc: 'Gigatonnes of Carbon Dioxide Equivalent (1 Billion tonnes). Used for global emissions tracking.' },
    { term: 'Net Zero', desc: 'A state in which the greenhouse gases going into the atmosphere are balanced by removal out of the atmosphere.' },
    { term: 'Climate Change', desc: 'Long-term shifts in temperatures and weather patterns, primarily caused by human activities, especially the burning of fossil fuels.' },
    { term: 'Renewable Energy', desc: 'Energy derived from natural sources that are replenished at a higher rate than they are consumed (e.g., sunlight, wind).' }
  ];

  return (
    <div className="max-w-4xl mx-auto space-y-6 animate-fade-in">
      <div className="flex items-center gap-3 mb-6">
        <div className="p-3 bg-purple-100 text-purple-600 rounded-xl">
          <BookOpen size={24} />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-gray-800">🎓 Learn Hub</h1>
          <p className="text-gray-500">Simple explanations for climate science terminology.</p>
        </div>
      </div>

      <div className="grid gap-4">
        {terms.map((t, i) => (
          <div key={i} className="bg-white p-5 rounded-2xl shadow-sm border border-gray-100 flex gap-4 items-start">
            <Info className="text-purple-400 shrink-0 mt-1" size={20} />
            <div>
              <h3 className="font-bold text-gray-800 text-lg">{t.term}</h3>
              <p className="text-gray-600 mt-1 leading-relaxed">{t.desc}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
